version: '3.8'

services:
  app:
    image: golang:1.22.0-alpine3.19
    container_name: todod
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=todod
      - DB_PASSWORD=todod
      - DB_NAME=todod
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1-alpine3.19
    container_name: postgres
    environment:
      - POSTGRES_USER=todod
      - POSTGRES_PASSWORD=todod
      - POSTGRES_DB=todod
    ports:
      - "5432:5432"
    # volumes:
    #   - ./configs/data:/var/lib/postgresql/data
