// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/google/uuid"
)

type Todo struct {
	Uuid        uuid.UUID
	Title       string
	Description string
}
